### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by armijnhemel** [prowave/chargify-webhook-java#21]
hello!

I can see that the license file is Apache 2, but some of the source code files have a GPL3 reference. Can you please clarify what the actual license is?

**Comment by pombredanne** [comment]
This may explain why? https://github.com/prowave/chargify-webhook-java/commit/5acbbb8172297a0a325f961cc7d46189ff5d70b2
Some oversight?

**Comment by prowave** [comment]
Which files have GPL references?  The `master` branch `LICENSE` file is the Apache LICENSE file that applies to this project.

**Comment by armijnhemel** [comment]
> Which files have GPL references? The `master` branch `LICENSE` file is the Apache LICENSE file that applies to this project.

All four files in:

https://github.com/prowave/chargify-webhook-java/tree/develop/src/main/java/io/prowave/chargify/webhook

and many (if not all) files in the 'bean' directory have a header that says something like:

     * Copyright (C) 2016 Prowave Consulting, LLC
     *
     * This program is free software: you can redistribute it and/or modify
     * it under the terms of the GNU General Public License as published by
     * the Free Software Foundation, either version 3 of the License, or
     * (at your option) any later version.
     *
     * This program is distributed in the hope that it will be useful,
     * but WITHOUT ANY WARRANTY; without even the implied warranty of
     * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     * GNU General Public License for more details.
     *
     * You should have received a copy of the GNU General Public License
     * along with this program.  If not, see <http://www.gnu.org/licenses/>.

I guess that during the relicense of the code these were forgotten to be changed.

**Comment by prowave** [comment]
Thanks for pointing that out. You can create a PR from `develop` if you would like.

**Comment by prowave** [comment]
Version 1.1.6 merged and published to maven central.
