### ISSUE TITLE
Go port

### ISSUE THREAD

**Issue by m0dd3r** [prowave/chargify-webhook-java#7]
Hi, just wanted to let you know that I liked your library so much, I ported it to Go. Well, part of it at least. I still have a lot of message types to add, but the majority of the core functionality, i.e. the parser and message factory stuff is there. I put a link to this repo in the README to make sure you got credit. Just thought I'd share and say thanks for the work. https://github.com/m0dd3r/chargify-webhook-golang

**Comment by prowave** [comment]
Thank you.
